name: Deploy Contoso_University_Staging
on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: 'TestSolution'
jobs:
  deploy:
    runs-on: windows-latest
    environment: 'Contoso-University-Staging'
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/pack-solution@v0
        with:
          solution-file: out/${{ github.event.inputs.solution_name }}.zip 
          solution-folder: contents/${{ github.event.inputs.solution_name }}
          solution-type: Both
      - uses: microsoft/powerplatform-actions/import-solution@v0
        with:
          environment-url: ${{ vars.POWERPLATFORMURL }}
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-file: ${{ github.event.inputs.solution_name }}_managed.zip