name: Pack Costoso-University-Staging
on:
  push:
    paths:
      - contents/**
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'name of the solution to worked on from Power Platform'
        required: true
        default: 'Test-Solution'
jobs:
  build:
    runs-on: windows-latest
    environment: 'Contoso-University-Dev'
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          solution-name: ${{ github.event.inputs.solution_name }}
          environment-url: ${{ vars.POWERPLATFORMURL }}
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-output-file: ${{ github.event.inputs.solution_name }}_managed.zip
          managed: true
      - uses: microsoft/powerplatform-actions/export-solution@v0
        with:
          solution-name: ${{ github.event.inputs.solution_name }}
          environment-url: ${{ vars.POWERPLATFORMURL }}
          user-name: ${{ secrets.USERNAME }}
          password-secret: ${{ secrets.PASSWORD }}
          solution-output-file: ${{ github.event.inputs.solution_name }}.zip
          managed: false

      - uses: microsoft/powerplatform-actions/unpack-solution@v0
        with:
          solution-file: ${{ github.event.inputs.solution_name }}.zip
          solution-folder: contents/${{ github.event.inputs.solution_name }}
          solution-type: Both
          overwrite-files: true